name: Build Clean Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove unwanted files
        run: |
          rm -rf .git
          rm -f README.md
          rm -f .gitattributes
          rm -f .gitignore

      - name: Create ZIP
        run: zip -r RoarOptimizationsV1.2.zip .

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: RoarOptimizationsV1.2.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
